title: Code for San Francisco Finance
description: >
  Code for San Francisco finances and fundraising opportunities
baseurl: "/fund-site"
url: "http://codeforsanfrancisco.org"
twitter_username: sfbrigade
github_username:  sfbrigade

# Build settings
markdown: kramdown
