title: Code for San Francisco Finance
description: >
  Code for San Francisco finances and fundraising opportunities
baseurl: ""
url: "http://fund.codeforsanfrancisco.org" # the base hostname & protocol for your site
twitter_username: sfbrigade
github_username:  sfbrigade

# Build settings
markdown: kramdown
